apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: dotnet-integration-test
  namespace: testkube
spec:
  content:
    git:
      uri: https://github.com/sanglap-02/testkubeTest
      revision: master
      paths:
        - EndToEndAutomationTesting
  container:
    workingDir: /data/repo/EndToEndAutomationTesting
    image: mcr.microsoft.com/dotnet/sdk:8.0
    resources:
      requests:
        cpu: 512m
        memory: 512Mi
    shell: bash
    setupScript: |
      apt-get update
      apt-get install -y curl unzip chromium
      
      # Download latest ChromeDriver version
      CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
      echo "Using ChromeDriver version $CHROME_DRIVER_VERSION"
      
      wget -q -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip"
      unzip -o /tmp/chromedriver.zip -d /usr/local/bin
      chmod +x /usr/local/bin/chromedriver
      
      # Ensure symlink for Chromium is created for compatibility
      ln -s /usr/bin/chromium /usr/bin/google-chrome
      
      # Verify installations
      chromium --version
      chromedriver --version
  steps:
    - name: Restore packages
      shell: dotnet restore EndToEndAutomationTesting.sln

    - name: Build application
      shell: dotnet build EndToEndAutomationTesting.sln

    - name: Run tests
      shell: dotnet test EndToEndAutomationTesting.sln --logger:"trx;LogFileName=test-results.trx"
      artifacts:
        paths:
          - TestResults/*
