apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: dotnet-integration-test
  namespace: testkube
spec:
  content:
    git:
      uri: https://github.com/sanglap-02/testkubeTest
      revision: master
      paths:
        - EndToEndAutomationTesting
  container:
    workingDir: /data/repo/EndToEndAutomationTesting
    image: mcr.microsoft.com/dotnet/sdk:8.0
    resources:
      requests:
        cpu: 512m
        memory: 512Mi
  steps:
    - name: Restore packages
      shell: dotnet restore EndToEndAutomationTesting.sln

    - name: Build application
      shell: dotnet build EndToEndAutomationTesting.sln

    - name: Run tests
      shell: dotnet test EndToEndAutomationTesting.sln --logger:"trx;LogFileName=test-results.trx"
      artifacts:
        paths:
          - TestResults/*
