apiVersion: testworkflows.testkube.io/v3
kind: TestWorkflow
metadata:
  name: integration-test
spec:
  input:
    files:
      - path: .
  steps:
    - name: Restore NuGet packages
      run:
        image: mcr.microsoft.com/dotnet/sdk:8.0
        workingDir: /data/repo
        command: ["dotnet", "restore", "EndToEndAutomationTesting.sln"]
    - name: Build the solution
      run:
        image: mcr.microsoft.com/dotnet/sdk:8.0
        workingDir: /data/repo
        command: ["dotnet", "build", "EndToEndAutomationTesting.sln", "-c", "Release", "--no-restore"]
    - name: Run tests
      run:
        image: mcr.microsoft.com/dotnet/sdk:8.0
        workingDir: /data/repo
        command: ["dotnet", "test", "EndToEndAutomationTesting.sln", "-c", "Release", "--no-build", "--logger:trx"]
